# Youll need to make a volumes for tmp/ and public/storage

version: "3"

services:

  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: api