# Youll need to make a volumes for tmp/ and public/storage

version: "3"

services:
  proxy:
    restart: always
    container_name: proxy
    build:
      context: .
      dockerfile: ./docker/nginx/local.nginx.dockerfile
    ports:
      - 443:443
      - 80:80

  api:
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: api
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    environment:
      - HTTP_PORT=8080
      - TOKEN_SECRET=sadsa123za
      - DB_URL=mongodb://db:27017/chat
  db:
    restart: always
    container_name: db
    image: mongo:4
    volumes:
      - ./data:/data/db
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    container_name: web
