# Youll need to make a volumes for tmp/ and public/storage

version: "3"

services:
  proxy:
    restart: always
    container_name: proxy
    build:
      context: .
      dockerfile: ./docker/nginx/local.nginx.dockerfile
    ports:
#      - 443:443
      - 8080:80

  api:
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api:/usr/src/app
    environment:
      - HTTP_PORT=80
      - TOKEN_SECRET=sadsa123za
      - DB_URL=mongodb://db:27017/chat
  db:
    restart: always
    container_name: db
    image: mongo:4
    volumes:
      - ./data:/data/db
    ports:
         - 27017:27017
  web:
    restart: always
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
        - 8000:3000
    environment:
      - PORT=8000
