# Youll need to make a volumes for tmp/ and public/storage

version: "3"

services:

  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: api
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - HTTP_PORT=8080
      - TOKEN_SECRET=sadsa123za
      - DB_URL=mongodb://db:27017/chat
  db:
    restart: always
    container_name: db
    image: mongo:4
    volumes:
      - ./data:/data/db

